version: "3.9"
services:
  order_service_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_service_server
    restart: on-failure
    ports:
      - 8094:8094
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/order_service}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-root}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD:-root}"
      SPRING_RABBITMQ_HOST: "${RABBITMQ_HOST:-rabbitmq}"
      SPRING_RABBITMQ_PORT: "${RABBITMQ_PORT:-5672}"
      SPRING_RABBITMQ_USERNAME: "${RABBITMQ_USERNAME:-user}"
      SPRING_RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD:-password}"
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATA_REDIS_HOST: "${SPRING_DATA_REDIS_HOST:-redis}"
      SPRING_DATA_REDIS_PORT: "${SPRING_DATA_REDIS_PORT:-6379}"
    networks:
      - ku-wongnai_ku-wongnai

networks:
  ku-wongnai_ku-wongnai:
    external: true
